# Creación y compra de claves juegos

In [1]:
import mysql.connector
import pandas as pd 
from mysql.connector import errorcode
import random
from datetime import datetime
try:
    cnx = mysql.connector.connect(
      host="localhost",
      user="root",
      database='stum_for_you',
      passwd=""
    )
except mysql.connector.Error as err:
    if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
        print("Something is wrong with your user name or password")
    elif err.errno == errorcode.ER_BAD_DB_ERROR:
        print("Database does not exist")
    else:
        print(err)



cursor = cnx.cursor()
for auxiliar in range(0,100):
    #elegimos un juego
    cursor.execute("SELECT COUNT(*) FROM juegos")
    numjuegos = cursor.fetchone()[0] + 1
    id_juego = random.randrange(1,numjuegos)
    sql = """SELECT * FROM juegos WHERE id_juego = %s """ % (id_juego)
    cursor.execute(sql)
    juego = cursor.fetchone()
    #elegimos un proveedor
    cursor.execute("SELECT COUNT(*) FROM proveedor")
    numprov = cursor.fetchone()[0] + 1
    id_proveedor = random.randrange(1,numprov)
    sql = """SELECT * FROM proveedor WHERE id_proveedor = %s """ % (id_proveedor)
    cursor.execute(sql)
    proveedor = cursor.fetchone()
    # añadimos a la tabla transacción compra
    elem = random.randrange(1,100)
    sql = "INSERT INTO transacciones_compra (precio_total, fecha_compra) VALUES (%s, %s)"
    descuento =  random.randrange(1,10) /10
    print(descuento)
    preciojuego=int(juego[3]*descuento )

    #fecha= aleatoriofecha
    inicio = datetime(2017, 1, 30)
    final =  datetime(2020, 1, 1)
    fecha = inicio + (final - inicio) * random.random()

    val = (preciojuego * elem, fecha)
    cursor.execute(sql,val)
    cnx.commit()
    cursor.execute("SELECT MAX(id_transaccion) FROM transacciones_compra")
    id_transac = cursor.fetchone()[0]
    # añadimos clave
    print(elem)
    for i in range (0, elem) :
        aux = True
        while aux :
            num1 = str(random.randrange(1,999999))
            num2 = str(random.randrange(1,9999))
            clave = num1.zfill(6) + '-' + num2.zfill(4)
            sql = """SELECT * FROM claves_juegos WHERE clave = %s """ % (clave)
            cursor.execute(sql)
            if(len(cursor.fetchall()) == 0) :
                aux = False
        sql = "INSERT INTO claves_juegos (clave, fecha_anexion, id_juego) VALUES (%s, %s, %s)"
        val = (clave, fecha, id_juego)
        cursor.execute(sql,val)
        cnx.commit()
        cursor.execute("SELECT MAX(id_clave) FROM claves_juegos")
        id_clave = cursor.fetchone()[0]




        # añadimos compra
        sql = "INSERT INTO compra_juegos (id_proveedor, id_transaccion, id_claves_juego, precio) VALUES (%s, %s, %s, %s)"
        val = (id_proveedor, id_transac, id_clave, preciojuego)
        cursor.execute(sql,val)
        cnx.commit()
       # print("proveedor :" , id_proveedor , "id_transac :" , id_transac ,"id_clave :" , id_clave , "preciojuegoD :" 
          #    , preciojuego , "preciojuego :", juego[3])

0.7
50
0.9
18
0.7
98
0.5
96
0.7
74
0.5
23
0.3
93
0.4
14
0.5
75
0.8
16
0.7
30
0.2
49
0.4
15
0.5
69
0.5
12
0.7
23
0.6
16
0.8
61
0.1
39
0.8
41
0.9
27
0.8
79
0.6
61
0.5
57
0.4
61
0.5
91
0.6
16
0.6
50
0.6
51
0.7
46
0.4
87
0.3
45
0.3
3
0.2
21
0.7
26
0.2
36
0.7
44
0.9
35
0.8
86
0.1
94
0.5
89
0.1
43
0.4
7
0.4
58
0.5
86
0.1
37
0.5
85
0.9
69
0.2
80
0.8
60
0.8
46
0.8
52
0.2
57
0.8
74
0.5
38
0.2
35
0.1
94
0.9
16
0.7
30
0.7
30
0.1
91
0.8
94
0.8
35
0.9
3
0.6
5
0.7
19
0.9
97
0.9
17
0.4
31
0.4
47
0.9
31
0.5
47
0.8
42
0.2
40
0.5
1
0.8
96
0.9
15
0.4
29
0.8
44
0.6
12
0.3
47
0.9
77
0.2
51
0.2
80
0.4
57
0.6
73
0.9
53
0.7
98
0.3
1
0.7
85
0.1
57
0.9
69
0.5
71
0.9
4
0.4
64
0.7
23
0.2
86
0.7
3
0.9
85
0.9
92

# Creación y compra de claves dlcs

In [2]:
import mysql.connector
import pandas as pd 
from mysql.connector import errorcode
import random
from datetime import datetime
try:
    cnx = mysql.connector.connect(
      host="localhost",
      user="root",
      database='stum_for_you',
      passwd=""
    )
except mysql.connector.Error as err:
    if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
        print("Something is wrong with your user name or password")
    elif err.errno == errorcode.ER_BAD_DB_ERROR:
        print("Database does not exist")
    else:
        print(err)



cursor = cnx.cursor()
for auxiliar in range(0,70):
    #elegimos un dlc
    cursor.execute("SELECT COUNT(*) FROM dlcs")
    numdlcs = cursor.fetchone()[0] + 1
    id_dlc = random.randrange(1,numdlcs)
    sql = """SELECT * FROM dlcs WHERE id_dlc = %s """ % (id_dlc)
    cursor.execute(sql)
    dlc = cursor.fetchone()
    #elegimos un proveedor
    cursor.execute("SELECT COUNT(*) FROM proveedor")
    numprov = cursor.fetchone()[0] + 1
    id_proveedor = random.randrange(1,numprov)
    sql = """SELECT * FROM proveedor WHERE id_proveedor = %s """ % (id_proveedor)
    cursor.execute(sql)
    proveedor = cursor.fetchone()
    # añadimos a la tabla transacción compra
    elem = random.randrange(1,100)
    sql = "INSERT INTO transacciones_compra (precio_total, fecha_compra) VALUES (%s, %s)"
    descuento =  random.randrange(1,10) /10
    #print(descuento)
    preciodlc=int(dlc[1]*descuento)

    #fecha= aleatoriofecha
    inicio = datetime(2017, 1, 30)
    final =  datetime(2020, 1, 1)
    fecha = inicio + (final - inicio) * random.random()

    val = (preciodlc * elem, fecha)
    cursor.execute(sql,val)
    cnx.commit()
    cursor.execute("SELECT MAX(id_transaccion) FROM transacciones_compra")
    id_transac = cursor.fetchone()[0]
    # añadimos clave
    #print(elem)
    for i in range (0, elem) :
        aux = True
        while aux :
            num1 = str(random.randrange(1,999999))
            num2 = str(random.randrange(1,9999))
            clave = num1.zfill(6) + '#' + num2.zfill(4)
            sql = """SELECT * FROM claves_dlc WHERE clave = %s """ % (clave)
            cursor.execute(sql)
            if(len(cursor.fetchall()) == 0) :
                aux = False
        sql = "INSERT INTO claves_dlc (clave, fecha_anexion, id_dlc) VALUES (%s, %s, %s)"
        val = (clave, fecha, id_dlc)
        cursor.execute(sql,val)
        cnx.commit()
        cursor.execute("SELECT MAX(id_clave) FROM claves_dlc")
        id_clave = cursor.fetchone()[0]




        # añadimos compra
        sql = "INSERT INTO compra_dlcs (id_proveedor, id_transaccion, id_claves_dlc, precio) VALUES (%s, %s, %s, %s)"
        val = (id_proveedor, id_transac, id_clave, preciodlc)
        cursor.execute(sql,val)
        cnx.commit()
        #print("proveedor :" , id_proveedor , "id_transac :" , id_transac ,"id_clave :" , id_clave , "precioDLCD :" 
          #   , preciodlc , "preciodlc :", dlc[3])